/**
 * Sabit Müfredat (Hardcoded Curriculum)
 * 
 * Bu dosya MEB müfredatına göre tanımlanmış konuları içerir.
 * OCR ve analiz motorları SADECE bu listedeki konuları kabul eder.
 * Listedeki isimle eşleşmeyen hiçbir konu veritabanına kaydedilmez.
 * 
 * Bu listeyi güncellemek için:
 * 1. Sınıf/Sınav anahtarını (örn: "12. Sınıf", "TYT") kullanın
 * 2. Ders anahtarını (örn: "Matematik") kullanın
 * 3. Konu dizisine resmi MEB konu adlarını ekleyin
 */

export const CURRICULUM: Record<string, Record<string, string[]>> = {
  "TYT": {
    "Türkçe": [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragraf",
      "Sözcük Türleri",
      "İsim",
      "Zamir",
      "Sıfat",
      "Zarf",
      "Edat",
      "Bağlaç",
      "Ünlem",
      "Tamlamalar",
      "Fiil",
      "Ek Fiil",
      "Fiilimsi",
      "Ekler",
      "Sözcük Yapısı",
      "Cümlenin Öğeleri",
      "Cümle Çeşitleri",
      "Ses Bilgisi",
      "Anlatım Bozuklukları",
      "Yazım Kuralları",
      "Noktalama İşaretleri"
    ],
    "Matematik": [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme – Bölünebilme Kuralları",
      "EBOB-EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Denklem Çözme",
      "Oran-Orantı",
      "Problemler",
      "Kümeler",
      "Mantık",
      "Fonksiyonlar",
      "Permütasyon-Kombinasyon",
      "Binom Açılımı",
      "Olasılık",
      "İstatistik",
      "Polinomlar"
    ],
    "Geometri": [
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Üçgende Eşlik ve Benzerlik",
      "Üçgende Açıortay",
      "Üçgende Kenarortay",
      "Üçgende Alan",
      "Özel Üçgenler",
      "Dik Üçgen",
      "İkizkenar Üçgen",
      "Eşkenar Üçgen",
      "Çokgenler",
      "Dörtgenler",
      "Yamuk",
      "Paralelkenar",
      "Eşkenar Dörtgen",
      "Deltoid",
      "Dikdörtgen",
      "Kare",
      "Çember ve Daire",
      "Katı Cisimler",
      "Dikdörtgenler Prizması",
      "Küp",
      "Silindir",
      "Piramit",
      "Koni",
      "Küre"
    ],
    "Fizik": [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Hareket ve Kuvvet",
      "İş, Güç ve Enerji",
      "Isı ve Sıcaklık",
      "Elektrostatik",
      "Elektrik ve Manyetizma",
      "Basınç",
      "Kaldırma Kuvveti",
      "Dalgalar",
      "Optik"
    ],
    "Kimya": [
      "Kimya Bilimi",
      "Atom ve Yapısı",
      "Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Kimyanın Temel Kanunları",
      "Kimyasal Tepkimeler ve Hesaplamalar",
      "Karışımlar",
      "Asitler, Bazlar ve Tuzlar",
      "Kimya Her Yerde"
    ],
    "Biyoloji": [
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Yapısı",
      "Canlıların Çeşitliliği ve Sınıflandırılması",
      "Hücre Bölünmeleri",
      "Kalıtım ve Biyolojik Çeşitlilik",
      "Ekosistem Ekolojisi ve Güncel Çevre Sorunları"
    ],
    "Tarih": [
      "İlk ve Orta Çağlarda Türk Dünyası",
      "Türklerin İslamiyeti Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti (1302-1453)",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti (1595-1774)",
      "Uluslararası İlişkilerde Denge Siyaseti",
      "19. ve 20. Yüzyılda Değişen Sosyoekonomik Hayat",
      "Milli Mücadele",
      "Atatürkçülük ve Atatürk İnkılapları"
    ],
    "Coğrafya": [
      "Doğal Sistemler",
      "Doğa ve İnsan Etkileşimi",
      "Coğrafya Bilimi ve Bölümlenmesi",
      "Dünya'nın Şekli ve Hareketleri",
      "Coğrafi Koordinat Sistemi",
      "Harita Okuryazarlığı",
      "Atmosfer ve İklim Bilgisi",
      "Dünya'nın Yapısı ve Oluşum Süreci",
      "Su Kaynakları",
      "Topraklar",
      "Bitkiler",
      "Beşeri Sistemler",
      "Yerleşmeler",
      "Nüfus ve Göç",
      "Ekonomik Faaliyetler",
      "Küresel Ortam: Bölgeler ve Ülkeler",
      "Bölgeler",
      "Uluslararası Ulaşım Hatları",
      "Afetler"
    ],
    "Felsefe": [
      "Felsefenin Anlamı",
      "Felsefe ile Düşünme",
      "Bilgi Felsefesi",
      "Bilim Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Siyaset Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi"
    ],
    "Din Kültürü": [
      "Bilgi ve İnanç",
      "Din ve İslam",
      "İslam ve İbadet",
      "Gençlik ve Değerler",
      "Gönül Coğrafyamız",
      "Allah İnsan İlişkisi",
      "Hz. Muhammed ve Gençlik",
      "Din ve Hayat",
      "Ahlaki Tutum ve Davranışlar",
      "İslam Düşüncesinde İtikadi, Siyasi ve Fıkhi Yorumlar",
      "Dünya ve Ahiret",
      "Kur'an'a Göre Hz. Muhammed",
      "Güncel Dinî Meseleler",
      "Anadolu'da İslam",
      "İslam Düşüncesinde Tasavvufi Yorumlar"
    ]
  },
  "AYT": {
    "Edebiyat": [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragrafta Anlam",
      "Şiir Bilgisi",
      "Söz Sanatları",
      "Metinlerin Sınıflandırılması",
      "İslamiyet Öncesi Türk Edebiyatı",
      "İslamiyet Etkisindeki Türk Edebiyatı",
      "Halk Edebiyatı",
      "Divan Edebiyatı",
      "Tanzimat Edebiyatı",
      "Servet-i Fünun Edebiyatı",
      "Fecr-i Ati Edebiyatı",
      "Milli Edebiyat",
      "Cumhuriyet Dönemi Türk Edebiyatı",
      "Geleneksel Türk Tiyatrosu",
      "Masal/Fabl/Destan/Halk Hikayesi",
      "Edebiyat Akımları"
    ],
    "Tarih": [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyeti Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti (1302-1453)",
      "Devletleşme Sürecinde Savaşçılar ve Askerler",
      "Dünya Gücü Osmanlı (1453-1595)",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
      "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
      "XIX ve XX. Yüzyılda Değişen Sosyoekonomik Hayat",
      "20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Millî Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
      "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
      "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
      "II. Dünya Savaşı Sonrasında Türkiye ve Dünya",
      "Toplumsal Devrim Çağında Dünya ve Türkiye",
      "21. Yüzyılın Eşiğinde Türkiye ve Dünya"
    ],
    "Coğrafya-1": [
      "Ekosistem Özellikleri ve İşleyişi",
      "Ekstrem Doğa Olayları",
      "Küresel İklim Değişikliği ve Doğa Olaylarının Geleceği",
      "Nüfus Politikaları ve Projeksiyonları",
      "Şehirler ve Kırsal Yerleşmeler",
      "Dünyada Doğal Kaynak ve Ekonomi",
      "Türkiye'de Tarım, Sanayi, Maden ve Enerji Kaynakları",
      "Ekonomi, Şehirleşme ve Göç",
      "İşlevsel Bölge ve Kalkınma Projeleri",
      "Hizmet Sektörü ve Ulaşım",
      "Türkiye'de ve Dünyada Ticaret",
      "Türkiye'de Turizm",
      "Kültür Bölgeleri ve Türk Kültürü",
      "Küreselleşen Dünya",
      "Uluslararası Örgütler",
      "Jeopolitik Konum ve Ülkeler Arası Etkileşim",
      "Çevre Sorunları ve Geri Dönüşüm"
    ],
    "Coğrafya-2": [
      "Ekosistem Özellikleri ve İşleyişi",
      "Ekstrem Doğa Olayları",
      "Küresel İklim Değişikliği ve Doğa Olaylarının Geleceği",
      "Nüfus Politikaları ve Projeksiyonları",
      "Şehirler ve Kırsal Yerleşmeler",
      "Dünyada Doğal Kaynak ve Ekonomi",
      "Türkiye'de Tarım, Sanayi, Maden ve Enerji Kaynakları",
      "Ekonomi, Şehirleşme ve Göç",
      "İşlevsel Bölge ve Kalkınma Projeleri",
      "Hizmet Sektörü ve Ulaşım",
      "Türkiye'de ve Dünyada Ticaret",
      "Türkiye'de Turizm",
      "Kültür Bölgeleri ve Türk Kültürü",
      "Küreselleşen Dünya",
      "Uluslararası Örgütler",
      "Jeopolitik Konum ve Ülkeler Arası Etkileşim",
      "Çevre Sorunları ve Geri Dönüşüm",
      "Çevre Sorunlarının Çözümüne Yönelik Yaklaşımlar"
    ],
    "Felsefe": [
      "Felsefeyi Tanıma",
      "Felsefe İle Düşünme",
      "Felsefenin Temel Konuları ve Problemleri",
      "Felsefi Okuma ve Yazma",
      "MÖ 6. Yüzyıl – MS 2. Yüzyıl Felsefesi",
      "MS 2. Yüzyıl – MS 15. Yüzyıl Felsefesi",
      "15. Yüzyıl – 17. Yüzyıl Felsefesi",
      "18. Yüzyıl – 19. Yüzyıl Felsefesi",
      "20. Yüzyıl Felsefesi"
    ],
    "Psikoloji": [
      "Psikoloji Bilimini Tanıyalım",
      "Psikolojinin Temel Süreçleri",
      "Öğrenme, Bellek, Düşünme",
      "Ruh Sağlığının Temelleri"
    ],
    "Sosyoloji": [
      "Sosyolojiye Giriş",
      "Birey ve Toplum",
      "Toplumsal Yapı",
      "Toplumsal Değişme ve Gelişme",
      "Toplum ve Kültür",
      "Toplumsal Kurumlar"
    ],
    "Mantık": [
      "Mantığa Giriş",
      "Klasik Mantık",
      "Mantık ve Dil",
      "Sembolik Mantık"
    ],
    "Din Kültürü": [
      "Gönül Coğrafyamız",
      "İslam ve İbadet",
      "Allah İnsan İlişkisi",
      "Hz. Muhammed ve Gençlik",
      "Din ve Hayat",
      "Ahlaki Tutum ve Davranışlar",
      "İslam Düşüncesinde İtikadi, Siyasi ve Fıkhi Yorumlar",
      "Dünya ve Ahiret",
      "Kur'an'a Göre Hz. Muhammed",
      "Kur'an'da Bazı Kavramlar",
      "İnançla İlgili Meseleler",
      "Yahudilik ve Hıristiyanlık",
      "İslam ve Bilim",
      "Anadolu'da İslam",
      "İslam Düşüncesinde Tasavvufi Yorumlar",
      "Güncel Dini Meseleler",
      "Hint ve Çin Dinleri"
    ],
    "Matematik": [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "OBEB-OKEK",
      "Rasyonel Sayılar",
      "Ondalıklı Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Denklem Çözme",
      "Oran-Orantı",
      "Problemler",
      "Mantık",
      "Kümeler",
      "Fonksiyonlar",
      "Polinomlar",
      "2. Dereceden Denklemler ve Eşitsizlikler",
      "Parabol",
      "Permütasyon",
      "Kombinasyon",
      "Binom",
      "Olasılık",
      "Karmaşık Sayılar",
      "Trigonometri",
      "Logaritma",
      "Diziler",
      "Limit ve Süreklilik",
      "Türev",
      "İntegral"
    ],
    "Geometri": [
      "Üçgenler",
      "Doğruda ve Üçgende Açılar",
      "Dik Üçgen",
      "Özel Üçgen",
      "İkizkenar ve Eşkenar Üçgen",
      "Açı Kenar Bağıntıları",
      "Üçgende Eşlik ve Benzerlik",
      "Üçgende Açıortay",
      "Üçgende Kenarortay",
      "Üçgende Alan",
      "Özel Dörtgenler",
      "Çokgenler ve Düzgün Çokgenler",
      "Paralelkenar",
      "Deltoid",
      "Eşkenar Dörtgen",
      "Kare",
      "Dikdörtgen",
      "Yamuk",
      "Çember ve Daire",
      "Noktanın Analitik İncelenmesi",
      "Doğrunun Analitik İncelenmesi",
      "Dönüşüm Geometrisi",
      "Katı Cisimler",
      "Çemberin Analitiği"
    ],
    "Fizik": [
      "Vektörler",
      "Kuvvet, Tork ve Denge",
      "Kütle Merkezi",
      "Basit Makineler",
      "Hareket",
      "Newton'ın Hareket Yasaları (Dinamik)",
      "İş, Güç ve Enerji II",
      "Atışlar",
      "Çembersel Hareket",
      "Dönme, Yuvarlanma ve Açısal Momentum",
      "Kütle Çekim ve Kepler Yasaları",
      "Basit Harmonik Hareket",
      "Dalga Mekaniği ve Elektromanyetik Dal.",
      "Atom Modelleri",
      "Büyük Patlama ve Parçacık Fiziği",
      "İtme ve Momentum",
      "Elektrik Alan ve Potansiyel",
      "Radyoaktivite",
      "Özel Görelilik",
      "Paralel Levhalar ve Sığa",
      "Manyetik Alan ve Manyetik Kuvvet",
      "Kara Cisim Işıması",
      "Fotoelektrik Olay ve Compton Olayı",
      "İndüksiyon, Alt. Akım ve Transformatörler",
      "Modern Fiziğin Teknolojideki Uygulamaları"
    ],
    "Kimya": [
      "Modern Atom Teorisi",
      "Gazlar",
      "Sıvı Çözeltiler ve Çözünürlük",
      "Kimyasal Tepkimelerde Enerji",
      "Kimyasal Tepkimelerde Hız",
      "Kimyasal Tepkimelerde Denge",
      "Kimya ve Elektrik",
      "Organik Kimya",
      "Enerji Kaynakları ve Bilimsel Gelişmeler"
    ],
    "Biyoloji": [
      "Sinir Sistemi",
      "Endoktrin Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım Sistemi",
      "Solunum Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Komünite Ekolojisi",
      "Popülasyon Ekolojisi",
      "Nükleik Asitlerin Keşfi ve Önemi",
      "Genetik Şifre ve Protein Sentezi",
      "Canlılık ve Enerji",
      "Fotosentez",
      "Kemosentez",
      "Hücresel Solunum",
      "Bitki Biyolojisi",
      "Canlılar ve Çevre"
    ]
  },
  "YDT": [
    "Kelime Bilgisi",
    "Dil Bilgisi",
    "Cloze Test",
    "Cümleyi Tamamlama",
    "İngilizce Cümlenin Türkçe Karşılığını Bulma",
    "Türkçe Cümlenin İngilizce Karşılığını Bulma",
    "Paragraf Anlamca Yakın Cümleyi Bulma",
    "Paragrafta Anlam Bütünlüğünü Sağlayacak Cümleyi Bulma",
    "Verilen Durumda Söylenecek İfadeyi Bulma",
    "Diyalog Tamamlama",
    "Anlam Bütünlüğünü Bozan Cümleyi Bulma"
  ],
  "9. Sınıf": {
    "Edebiyat": [
      "Edebiyat Nedir?",
      "Edebiyatın Güzel Sanatlarla İlişkisi",
      "Edebiyatın Diğer Bilimlerle İlişkisi",
      "Metinlerin Sınıflandırılması",
      "İletişim Nedir?",
      "İletişim Öğeleri",
      "Gösterge Çeşitleri",
      "Düşünceyi Geliştirme Yolları",
      "Dil Nedir?",
      "Dilin İşlevleri",
      "Dil-Kültür İlişkisi",
      "Dilin Kullanımından Doğan Türler",
      "Hikaye Nedir?",
      "Hikaye Türleri",
      "Hikayenin Tarihsel Gelişimi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "İsimler",
      "Şiir Nedir?",
      "Şiir Bilgisi",
      "Şiir Türleri",
      "Sıfatlar",
      "Masal Nedir?",
      "Fabl Nedir?",
      "Dinleme Türleri ve Etkili Dinlemenin İlkeleri",
      "Edatlar",
      "Bağlaçlar",
      "Ünlemler",
      "Roman Nedir?",
      "Roman Türleri",
      "Romanda Bakış Açıları",
      "Romanın Yapı Unsurları",
      "Zamirler",
      "Tiyatro Nedir?",
      "Tiyatronun Yapı Unsurları",
      "Tiyatro Terimleri",
      "Geleneksel Türk Tiyatrosu",
      "Zarflar",
      "Biyografi",
      "Otobiyografi",
      "CV / Öz Geçmiş",
      "Dilekçe Nedir?",
      "Tutanak Nedir?",
      "Fiil",
      "Mektup Nedir?",
      "Mektup Türleri",
      "E-Posta Nedir?",
      "Günlük Nedir?",
      "Blog Nedir?"
    ],
    "Matematik": [
      "Gerçek Sayıların Üslü ve Köklü Gösterimleri ile Yapılan İşlemler",
      "Gerçek Sayı Aralıkları ile Yapılan İşlemler",
      "Sayı Kümeleri ve İşlem Özellikleri",
      "İki Kare Farkı ve Tamkare Özdeşlikleri",
      "Gerçek Sayılarda Tanımlı Doğrusal Fonksiyonlar ve Mutlak Değer Fonksiyonlarının Nitel Özellikleri",
      "Doğrusal Fonksiyonlarla İfade Edilen Denklem ve Eşitsizlikler",
      "Algoritma Temelli Problemler",
      "Mantık Bağlaçları ve Niceleyiciler",
      "Üçgende Açı ve Kenarla İlgili Özellikler",
      "Üçgende Açı Özellikleri Arasındaki İlişkiler",
      "Üçgende Kenar Özellikleri Arasındaki İlişkiler",
      "Geometrik dönüşümlerle ilgili çıkarım yapabilme",
      "Geometrik Şekillerin Yansıma",
      "Öteleme ve Dönme Dönüşümleri Sonrası Görünüşü ve Bu Görünüşün Özellikleri",
      "Üçgenlerde Eşlik ve Benzerlik Koşulları",
      "Tek Nicel Değişken İçeren İstatistiksel Problemi Oluşturma",
      "Verileri Toplama ve Analize Hazır Hâle Getirme",
      "Bulgulara Ulaşma ve Bulguları Yorumlama",
      "İstatistiksel Görsel, Özet, Sonuç, Yorum, Çıkarım veya Tahminleri Değerlendirme",
      "Olayların Olasılığını Deneysel ve Teorik Olarak İnceleme",
      "Olayların Deneysel ve Teorik Olasılığını İlişkilendirme"
    ],
    "Fizik": [
      "Fizik Bilimi",
      "Fizik Biliminin Alt Dalları",
      "Fizik Bilimine Yön Verenler",
      "Fizik Bilimi İle İlgili Kariyer Keşfi",
      "Temel ve Türetilmiş Nicelikler",
      "Skaler ve Vektörel Nicelikler",
      "Vektörler",
      "Doğadaki Temel Kuvvetler",
      "Hareket ve Hareket Türleri",
      "Basınç",
      "Sıvılarda Basınç",
      "Açık Hava Basıncı",
      "Kaldırma Kuvveti",
      "Bernoulli İlkesi",
      "İç Enerji, Isı ve Sıcaklık Arasındaki İlişki",
      "Isı, Öz Isı, Isı Sığası ve Sıcaklık Farkı Arasındaki İlişki",
      "Hâl Değişimi",
      "Isıl Denge",
      "Isı Aktarım Yolları",
      "Isı İletim Hızı"
    ],
    "Kimya": [
      "Günlük Hayatta Kimya",
      "Kimyasal Maddelerin Kullanımı ve Güvenlik",
      "Kimyanın Alt Disiplinleri",
      "Kimya Alanında Kariyer Olanakları",
      "Atom Teorileri ve Atomun Yapısı",
      "Atom Orbitalleri ve Elektron Dizilimi",
      "Periyodik Tabloda Yer Bulma",
      "Periyodik Özellikler",
      "Metalik Bağ",
      "İyonik Bağ",
      "Kovalent Bağ",
      "Lewis Nokta Yapısı",
      "Molekül Polarlığı ve Apolarlığı",
      "Bileşiklerin Adlandırılması",
      "Moleküller Arası Etkileşimler",
      "Katılar ve Özellikleri",
      "Sıvılar ve Özellikleri",
      "Nanoparçacıklar ve Ekolojik Sürdürülebilirlik",
      "Metal Nanoparçacıklar",
      "Metal, Alaşım ve Metal Nanoparçacıkların Çevresel Etkileri",
      "Yeşil Kimyanın Atık Önleme İlkesi"
    ],
    "Biyoloji": [
      "Biyolojinin Önemi",
      "Biyoloji Biliminin Gelişimindeki Dönüm Noktaları",
      "Bilimin Doğası, Bilimsel Araştırma Süreçleri, Bilim Etiği",
      "Canlıların Ortak Özellikleri",
      "Sınıflandırmada Temel Yaklaşımlar ve Modern Sınıflandırma",
      "Üç Üst Âlem (Domain) Sisteminde Yer Alan Canlılar ve Genel Özellikleri (Bakteriler, Arkeler, Ökaryotlar)",
      "Biyoçeşitlilik",
      "Su",
      "Mineraller",
      "Karbonhidratlar",
      "Yağlar",
      "Proteinler",
      "Nükleik Asitler",
      "Vitaminler",
      "Prokaryot ve Ökaryot Hücre",
      "Hücre Zarı",
      "Sitoplazma",
      "Sitoplazmik Yapılar",
      "Organeller ve Çekirdek",
      "Hücre Zarından Madde Geçişleri",
      "Hücreden Doku",
      "Organ ve Sistemlerin Organizasyonu"
    ],
    "Tarih": [
      "Tarih Öğrenmenin Faydaları",
      "Tarihin Doğası",
      "Tarihsel Bilginin Üretim Süreci",
      "Tarih Araştırma ve Yazımında Dijitalleşme",
      "Tarım Devrimi'nin Eski Çağ Medeniyetlerindeki Yerleşmeye ve Ekonomiye Etkisi",
      "Eski Çağ Medeniyetlerinde Yönetim ve Ordu",
      "Eski Çağ Medeniyetlerinde Hukuk",
      "Eski Çağ'da İnançlar ile Bilim ve Sanat Anlayışları",
      "Türklerde Konargöçer Yaşam",
      "Orta Çağ'da Yaşanan Kitlesel Göçler",
      "Orta Çağ'daki Başlıca Devletlerin Yönetim ve Ordu Yapıları",
      "Orta Çağ'daki Ticaret Yolları",
      "Orta Çağ'daki Başlıca Medeniyet Havzalarında Bilim, Kültür ve Sanat"
    ],
    "Coğrafya": [
      "Coğrafya Biliminin Konusu ve Bölümleri",
      "Niçin Coğrafya Öğrenmeliyiz?",
      "Coğrafya Biliminin Gelişimi",
      "Mekânın Aynası Haritalar",
      "Türkiye'nin Coğrafi Konumu",
      "Mekânsal Bilgi Teknolojilerinin Bileşenleri",
      "Hava Olayları ve Günlük Hayata Etkileri",
      "İklim Sisteminin Bileşen ve Değişkenleri",
      "İklim Türleri",
      "İklim Sisteminde Yaşanan Değişiklikler",
      "Nüfusun Tarihsel Değişimi ve Geleceği",
      "Nüfusun Dağılışı ve Hareketleri",
      "Demografik Dönüşüm ve Nüfus Piramitleri",
      "Nüfusla İlgili Fırsat, Sorun ve Politikalar",
      "Ekonomik Faaliyetleri Etkileyen Coğrafi Faktörler",
      "Tehlike, Risk ve Afet",
      "Afet Türleri",
      "Bütüncül Afet Yönetimi",
      "Bölge ve Bölge Sınırı"
    ],
    "İngilizce": [
      "Studying Abroad",
      "My Environment",
      "Movies",
      "Human in Nature",
      "Inspirational People",
      "Bridging Cultures",
      "World Heritage",
      "Emergency and Health Problems",
      "Invitations and Celebrations",
      "Television and Social Media"
    ],
    "Almanca": [
      "Guten Tag! / İyi Günler!",
      "Erste Kontakte / İlk İletişim",
      "Länder und Sprachen / Ülkeler ve Diller",
      "Fertigkeitstraining / Alıştırmalar",
      "Im Klassenzimer / Sınıfta",
      "Mein Schultag / Benim Okul Günüm",
      "Treffpunkt AG / Buluşma Noktası",
      "Meine Familie – echt cool! / Ailem – gerçekten harika!",
      "Die Berufe / Meslekler",
      "Du siehst gut aus! / Harika görünüyorsun!",
      "Der Wecker klingelt / Çalar Saat Çalıyor",
      "Was machen wir am Wochenende / Hafta Sonu Ne Yapacağız",
      "Ein Treff im Café Timpi / Café Timpi'de Bir Toplantı",
      "Obst und Gemüse / Meyve ve Sebzeler",
      "Im Supermarkt / Süpermarkette",
      "Wir machen einen Kartoffelsalat / Patates Salatası Yapıyoruz",
      "Der Kalender / Takvim",
      "Die Überraschung / Sürpriz",
      "Tage zum Feiern / Kutlanacak Günler",
      "Tipps für die Freizeit / Boş Zamanınız İçin İpuçları",
      "Die Jugendlichen und ihre Hobbys / Gençler ve Hobileri",
      "Die Sportarten / Sporlar",
      "Meine Stadt / Benim Şehrim",
      "Meine Klamotten / Benim Kıyafetlerim",
      "Super! Wieder Ferien / Harika! Yeniden Tatil"
    ],
    "Din Kültürü": [
      "İnsan ve İnsanın Yaratılışı",
      "Doğruyu Arayan Bir Varlık Olarak İnsan",
      "İbadet ve Dua Eden Bir Varlık Olarak İnsan",
      "Kur'an'dan Mesajlar",
      "İman ve İmanın mahiyeti",
      "İslam'da İman Esasları",
      "İmanın Bireye ve Topluma Kazandırdıkları",
      "Kur'an'dan Mesajlar",
      "İslam'da İbadetin Kapsamı",
      "İslam'da Temel İbadetler",
      "İnsan ve İbadet",
      "Kur'an'dan Mesajlar",
      "İslam'da Ahlakın Mahiyeti",
      "Ahlakın Temel Unsurları",
      "Ahlaki Tutum ve Davranışlar",
      "Kur'an'dan Mesajlar",
      "Hz. Muhammed'in Beşerî ve Peygamberlik Yönü",
      "Hz. Muhammed'in Örnekliği",
      "Kültürümüzde Hz. Muhammed ve Ehlibeyt Sevgisi",
      "Kur'an'dan Mesajlar"
    ]
  },
  "10. Sınıf": {
    "Türk Dili ve Edebiyatı": [
      "Edebiyat-Tarih İlişkisi",
      "Edebiyat-Din İlişkisi",
      "Türklerin Kullandığı Alfabeler",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Halk Hikayesi",
      "Dede Korkut Hikayeleri",
      "Mesnevi",
      "Hikaye Nedir?",
      "Hikaye Türleri",
      "Fiilimsiler",
      "İslamiyetin Kabulünden Önceki Türk Edebiyatı",
      "Koşuk Nedir?",
      "Sagu Nedir?",
      "Sav Nedir?",
      "Geçiş Dönemi Eserleri ve Özellikleri",
      "İlahi Nedir?",
      "Nefes Nedir?",
      "Koşma Nedir?",
      "Mani",
      "Türkü",
      "Gazel",
      "Kaside",
      "Şarkı",
      "Destan Nedir?",
      "Destan Türleri",
      "Destan Örnekleri",
      "Efsane Nedir?",
      "Efsane Örnekleri",
      "Dünya Destanları",
      "İslamiyet'in Kabulünden Önceki Türk Edebiyatında Destan",
      "İslamiyet'in Kabulünden Sonraki Dönem Destanları",
      "1923-1980 Dönemi Türk Yapma Destanları",
      "Sıfat Tamlamaları",
      "Roman Nedir?",
      "Dünya Edebiyatında Roman",
      "Tanzimat Dönemi Türk Edebiyatında Roman",
      "Serveti Fünun Döneminde Roman",
      "Milli Edebiyat Döneminde Roman",
      "Cümle Çeşitleri",
      "Tiyatro Nedir?",
      "Geleneksel Türk Tiyatrosu",
      "Modern Türk Tiyatrosu",
      "Anı Nedir?",
      "Serveti Fünun Dönemi Türk Edebiyatında Anı",
      "Cumhuriyet Dönemi Türk Edebiyatında Anı",
      "Haber Yazısı Nedir?",
      "Güncel Gazete ve Dergi Haberleri",
      "Genel Ağ Haberleri",
      "Gezi Yazısı Nedir?",
      "Divan Edebiyatında Gezi Yazısı",
      "Cumhuriyet Edebiyatında Gezi Yazısı"
    ],
    "Matematik": [
      "Sayma ve Olasılık",
      "Fonksiyonlar",
      "Polinomlar",
      "İkinci Dereceden Denklemler",
      "Dörtgenler ve Çokgenler",
      "Katı Cisimler"
    ],
    "Fizik": [
      "Elektrik Akımı",
      "Potansiyel Fark",
      "Direnç",
      "Ohm Yasası",
      "Eşdeğer Direnç",
      "İç Direnç",
      "Elektromotor Kuvvet",
      "Elektrik Enerjisi",
      "Elektriksel Güç",
      "Manyetizma",
      "Katı Basıncı",
      "Akışkan Basınç",
      "Basınç Kuvveti",
      "Pascal Prensibi",
      "Bernoulli İlkesi",
      "Archimedes İlkesi",
      "Kaldırma Kuvveti",
      "Dalga, Titreşim",
      "Dalga Hareketi",
      "Dalga Boyu",
      "Periyot, Frekans",
      "Hız",
      "Genlik",
      "Atma",
      "Dalga Tepesi",
      "Dalga Çukuru",
      "Odak Noktası",
      "Merkez",
      "Stroboskop",
      "Rezonans",
      "Ses Yüksekliği",
      "Ses Şiddeti",
      "Tını, Yankı, Uğultu",
      "Gürültü, Ses kirliliği",
      "Deprem Dalgası",
      "Aydınlanma Şiddeti",
      "Işık Şiddeti",
      "Işık Akısı",
      "Gölge",
      "Yarı Gölge",
      "Yansıma",
      "Odak Noktası, Merkez",
      "Tepe Noktası, Asal Eksen",
      "Kırılma, Kırıcılık İndisi",
      "Snell Yasası",
      "Tam Yansıma, Sınır Açısı",
      "Görünür Uzaklık"
    ],
    "Kimya": [
      "Kimyanın Temel Kanunları",
      "Mol Kavramı",
      "Kimyasal Tepkimeler ve Denklemler",
      "Kimyasal Tepkimelerde Hesaplamalar",
      "Homojen ve Heterojen Karışımlar",
      "Ayrıştırma ve Saflaştırma Teknikleri",
      "Asitler",
      "Asitler ve Bazların Tepkimeleri",
      "Hayatımızda Asitler ve Bazlar",
      "Tuzlar",
      "Yaygın Günlük Hayat Kimyasalları",
      "Gıdalar"
    ],
    "Biyoloji": [
      "Mitoz ve Eşeysiz Üreme",
      "Mayoz ve Eşeyli Üreme",
      "Kalıtım ve Biyolojik Çeşitlilik",
      "Ekosistem Ekolojisi",
      "Güncel Çevre Sorunları ve İnsan",
      "Doğal Kaynaklar",
      "Biyolojik Çeşitliliğin Korunması"
    ],
    "Tarih": [
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Devleti",
      "Beylikten Devlete Osmanlı Siyaseti (1302-1453)",
      "Devletleşme Sürecinde Savaşçılar ve Askerler",
      "Beylikten Devlete Osmanlı Medeniyeti",
      "Dünya Gücü Osmanlı Devleti (1453-1595)",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Klasik Çağda Osmanlı Toplum Düzeni"
    ],
    "Coğrafya": [
      "Dünya'nın Tektonik Oluşumu",
      "Jeolojik Zamanlar",
      "Türkiye'nin Tektonizması",
      "İç Kuvvetler",
      "Kayaçlar ve Yeryüzü Şekilleri",
      "İç Kuvvetlerin Türkiye'deki Yeryüzü Şekillerinin Oluşum Sürecine Etkisi",
      "Dış Kuvvetler ve Yer Şekilleri",
      "Türkiye'de Dış Kuvvetler ve Yer Şekilleri",
      "Türkiye'nin Dağları, Ovaları ve Platoları",
      "Yeryüzündeki Su Kaynakları",
      "Okyanuslar",
      "Denizler",
      "Göller",
      "Akarsular",
      "Yeraltı Suları ve Kaynakları",
      "Türkiye'nin Su Kaynakları",
      "Yeryüzündeki Toprak Çeşitliliği",
      "Toprağın Oluşum Süreci",
      "Türkiye'deki Toprakların Dağılışı",
      "Türkiye Topraklarının Kullanımı",
      "Bitki Topluluklarının Sınıflandırılması ve Dağılışı",
      "Türkiye'deki Bitki Toplulukları ve Dağılışı",
      "Nüfus Özellikleri",
      "Dünya Nüfusunun Tarihsel Değişimi",
      "Nüfus Artış Hızı İle Ülkelerin Kalkınması Arasındaki İlişki",
      "Nüfusun Dağılışı, Nüfus Yoğunluğu ve Nüfus Piramitleri",
      "Türkiye Nüfusunun Dağılışı ve Yapısal Özellikleri",
      "Dünyada ve Türkiye'de Göçler",
      "Ekonomik Faaliyetler",
      "Uluslararası Ulaşım Hatlarının Küresel ve Bölgesel Etkileri",
      "Afetlerin Oluşum Nedenleri, Dağılışı ve Etkileri"
    ],
    "İngilizce": [
      "School Life",
      "Plans",
      "Legendary Figure",
      "Traditions",
      "Travel",
      "Helpful Tips",
      "Food and Festivals",
      "Digital Era",
      "Modern Heroes and Heroines",
      "Shopping"
    ],
    "Felsefe": [
      "Felsefe Nedir?",
      "Felsefe Terimi",
      "Felsefe Tanımları",
      "Düşünmenin Önemi ver Gerekliliği",
      "Felsefi Düşünce",
      "Felsefi Düşüncenin Ortaya Çıkışı",
      "Felsefi Düşüncenin Nitelikleri",
      "Felsefenin İnsan ve Toplum Hayatındaki Rolü",
      "Felsefenin Bireysel ve Toplumsal İşlevi",
      "Felsefe‐ Hayat İlişkisi",
      "Akıl Yürütmeye ve Düşünmeye İlişkin Temel Kavramlar",
      "Akıl Yürütme ve Argümantasyon",
      "Dili Doğru Kullanmanın Önemi",
      "Dilin İşlevi",
      "Felsefi Sorular Nitelikleri ve Diğer Sorulardan Farkı",
      "Felsefi Soru Oluşturma",
      "Görüş Veya Argümanların Analizi",
      "Felsefenin Temel Konuları ve Problemleri",
      "Varlık Felsefesinin Konusu ve Problemleri",
      "Varlığın Hakikati ve Bilgisi",
      "Varlığın Mahiyeti",
      "Evrende Amaçlılık",
      "Bilgi Felsefesinin Konusu ve Problemleri",
      "Doğru Bilginin İmkanı",
      "Bilginin Kaynağı",
      "Bilginin Sınırları",
      "Bilginin Sınırları ve Doğru Bilginin Ölçütleri",
      "Bilginin Güvenirliliği ve Değeri",
      "Bilim Felsefesinin Konusu ve Problemleri",
      "Bilim ve Bilimsel Yöntem",
      "Bilimin Değeri",
      "Bilim ve Felsefe İlişkisi",
      "Ahlak Felsefesinin Konusu ve Problemleri",
      "İyi ve Kötü",
      "Özgürlük ve Sorumluluk",
      "Evrensel Ahlak Yasası",
      "Din Felsefesinin Konusu ve Soruları",
      "Teoloji ve Din Felsefesi",
      "Tanrı'nın Varlığı İle İlgili Görüşler",
      "Evrenin Sonlu Olup Olmadığı İle İlgili Görüşler",
      "Ölümden Sonra Yaşamın Olup Olmadığı İle İlgili Görüşler",
      "Siyaset Felsefesinin Konusu ve Problemleri",
      "Hak, Adalet, Özgürlük",
      "İktidarın Kaynağı",
      "İdeal Devlet Düzeni",
      "Temel Hak ve Özgürlükler Açısından Egemenlik Sorunu",
      "Sanat Felsefesinin Konusu ve Problemleri",
      "Güzellik",
      "Sanat",
      "Sanat Eserinin Özellikleri",
      "Felsefi Metin Analizi",
      "Alternatif Görüş Geliştirme",
      "Felsefi Deneme Yazma",
      "Akıl Yürütme Becerileri",
      "Felsefi Akıl Yürütme Becerilerinin Diğer Alanlarda Kullanımı"
    ],
    "Din Kültürü": [
      "Allah İnancı ve İnsan",
      "Allah'ın Varlığı ve Birliği",
      "Allah'ın İsim ve Sıfatları",
      "Kur'an-ı Kerim'de İnsan ve Özellikleri",
      "İnsanın Allah İle İrtibatı",
      "Kur'an'dan Mesajlar: Rûm Suresi 18-27. Ayetler",
      "Kur'an-ı Kerim'de Gençler",
      "Bir Genç Olarak Hz. Muhammed",
      "Hz. Muhammed ve Gençler",
      "Bazı Genç Sahabiler: Bilge ve Kahraman Bir Genç: Hz. Ali",
      "Genç Bir Davetçi: Erkam b. Ebi'l-Erkam",
      "Genç Bir Öğretmen: Mus'ab b. Umeyr",
      "Genç Bir Komutan: Üsame b. Zeyd",
      "Genç Bir Yönetici: Muaz b. Cebel",
      "Genç Bir Âlim: Hz. Aişe",
      "Genç Bir Anne: Hz. Fatıma",
      "Sorumluluk Sahibi Bir Genç: Esma binti Ebi Bekir",
      "Bazı Genç Sahabiler: Habeş Kralının Huzurunda Bir Genç: Cafer b. Ebi Talib",
      "Kur'an'dan Mesajlar: Âl-i İmrân Suresi 159. Ayet",
      "Din ve Aile",
      "Din, Kültür ve Sanat",
      "Din ve Çevre",
      "Din ve Sosyal Değişim",
      "Din ve Ekonomi",
      "Din ve Sosyal Adalet",
      "Kur'an'dan Mesajlar: Âl-i İmrân Suresi 103-105. Ayetler",
      "İslam Ahlakının Konusu ve Gayesi",
      "İslam Ahlakının Kaynakları",
      "Din ve Ekonomi",
      "Din ve Sosyal Adalet",
      "Kur'an'dan Mesajlar: Âl-i İmrân Suresi 103-105. Ayetler",
      "İslam Ahlakının Konusu ve Gayesi",
      "Dinî Yorum Farklılıklarının Sebepleri",
      "Dinî Yorumlarla İlgili Bazı Kavramlar",
      "İslam Düşüncesinde İtikadi ve Siyasi Yorumlar: Ehl-i sünnet (Eşarilik ve Maturidilik)",
      "Şia (İmamiye ve Zeydiye)",
      "İslam Düşüncesinde Fıkhi Yorumlar: Hanefilik",
      "Malikilik",
      "Şafiilik",
      "Hanbelilik",
      "Caferilik",
      "Kur'an'dan Mesajlar: Nisâ Suresi 59. Ayet"
    ]
  },
  "11. Sınıf": {
    "Türk Edebiyatı": [
      "Edebiyat-Toplum İlişkisi",
      "Edebiyatın Sanat Akımları ile İlişkisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Hikaye Nedir?",
      "Cumhuriyet Dönemi'nde (1923-1940 arası) Hikaye",
      "Küçürek (Minimal) Hikaye",
      "Kelimede Anlam",
      "Şiir Nedir?",
      "Tanzimat Dönemi Şiir",
      "Servetifünun Şiir",
      "Saf Şiir Anlayışına Bağlı Şiir",
      "Milli Edebiyat Döneminde Şiir",
      "Türk Dünyası Edebiyatında Şiir",
      "Makale Nedir?",
      "Bilimsel Makale",
      "Edebi Makale",
      "Sohbet (Söyleşi) Nedir?",
      "Fıkra (Köşe Yazısı) Nedir?",
      "Cumhuriyet Öncesi Dönemde ve Cumhuriyet Döneminde Sohbet",
      "Cumhuriyet Öncesi Dönemde ve Cumhuriyet Döneminde Fıkra",
      "Roman Nedir?",
      "Cumhuriyet Dönemi Romanı",
      "Dünya Edebiyatında Roman",
      "Anlatım Bozukluğu",
      "Tiyatro Nedir?",
      "Cumhuriyet Dönemi'nde Tiyatro",
      "Dünya Edebiyatında Tiyatro",
      "Eleştiri Nedir?",
      "Cumhuriyet Döneminde Eleştiri",
      "Cumhuriyet Öncesi Dönem'de Eleştiri",
      "Mülakat Nedir?",
      "Röportaj Nedir?",
      "Cumhuriyet Öncesi Dönem'de Mülakat",
      "Cumhuriyet Dönemi'nde Röportaj"
    ],
    "Matematik": [
      "Yönlü Açılar",
      "Trigonometrik Fonksiyonlar",
      "Doğrunun Analitik İncelemesi",
      "Modüler Artimetik ve İşlemler",
      "Fonksiyonlarla İlgili Uygulamalar",
      "İkinci Dereceden Fonksiyonlar ve Grafikleri",
      "Fonksiyonların Dönüşümleri",
      "İkinci Dereceden İki Bilinmeyenli Denklem Sistemleri",
      "İkinci Dereceden Bir Bilinmeyenli Eşitsizlikler ve Eşitsizlik Sistemleri",
      "Çemberin Temel Elemanları",
      "Çemberde Açılar",
      "Çemberde Teğet",
      "Dairenin Çevresi ve Alanı",
      "Katı Cisimler",
      "Olasılık"
    ],
    "Fizik": [
      "Vektörler",
      "Bağıl Hareket",
      "Newton'un Hareket Yasaları",
      "Bir Boyutta Sabit İvmeli Hareket",
      "İvmeli Hareket",
      "Serbest Düşme",
      "Limit Hız",
      "Düşey Atış",
      "Yatay Atış",
      "İki Boyutta Sabit İvmeli Hareket",
      "Eğik Atış",
      "Enerji ve Hareket",
      "Hooke Yasası",
      "İtme ve Çizgisel Momentum",
      "İtme",
      "Çizgisel Momentum",
      "Çizgisel Momentumun Korunumu",
      "Tork ve Denge",
      "Tork",
      "Denge",
      "Kütle Merkezi",
      "Ağırlık Merkezi",
      "Elektriksel kuvvet",
      "Elektrik Alan",
      "Elektriksel Potansiyel Enerji",
      "Elektriksel Potansiyel",
      "Elektriksel Potansiyel Farkı",
      "Sığa (Kapasite)",
      "Manyetik Alan",
      "Manyetik Kuvvet",
      "Manyetik Akı",
      "Elektromotor Kuvveti",
      "Alternatif Akım",
      "İndüktans, Kapasitans, Empedans",
      "Rezonans",
      "İndüksiyon Akımı",
      "Özindüksiyon Akımı",
      "Transformatör"
    ],
    "Kimya": [
      "Atomun Kuantum Modeli",
      "Periyodik Sistem ve Elektron Dizilimleri",
      "Periyodik Özellikler",
      "Elementleri Tanıyalım",
      "Yükseltgenme Basamakları",
      "Gazların Özellikleri ve Gaz Yasaları",
      "İdeal Gaz Yasası",
      "Gazlarda Kinetik Teori",
      "Gaz Karışımları",
      "Gerçek Gazlar",
      "Çözücü ve Çözünen Etkileşimleri",
      "Derişim Bilimleri",
      "Koligatif Özellikler",
      "Çözünürlük",
      "Koligatif Özellikler",
      "Çözünürlük",
      "Çözünürlüğe Etki Eden Faktörler",
      "Tepkimelerde Isı Değişimi Oluşum Entalpisi",
      "Bağ Enerjileri Tepkime Isılarının Toplanabilirliği",
      "Tepkime Hızları",
      "Tepkime Hızına Etki Eden Faktörler",
      "Kimyasal Denge",
      "Dengeye Etki Eden Faktörler",
      "Sulu Çözelti Dengeleri"
    ],
    "Biyoloji": [
      "Denetleyici ve Düzenleyici Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım Sistemi",
      "Solunum Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Komünite Ekolojisi",
      "Popülasyon Ekolojisi"
    ],
    "Tarih": [
      "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi",
      "Uluslararası İlişkilerde Denge Stratejisi",
      "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
      "Sermaye ve Emek",
      "19. ve 20. Yüzyılda Değişen Gündelik Hayat"
    ],
    "Coğrafya": [
      "Biyoçeşitlilik",
      "Madde Döngüleri ve Enerji Akışı",
      "Su Ekosistemleri",
      "Nüfus Politikaları",
      "Türkiye'nin Nüfus Politikaları",
      "Türkiye'nin Nüfus Projeksiyonları",
      "Şehirlerin Fonksiyonel Özellikleri ve Etki Alanları",
      "Türkiye'deki Şehirlerin Fonksiyonel Özellikleri ve Kır Yerleşme Tipl",
      "Doğal ve Beşeri Unsurların Üretim, Dağıtım ve Tüketim Üzerindeki Etkisi",
      "Doğal Kaynaklar",
      "Türkiye'deki Doğal Kaynaklar",
      "Türkiye'de Uygulanan Ekonomi Politikaları",
      "Türkiye Ekonomisinin Sektörel Dağılımı",
      "Türkiye'de Tarım, Hayvancılık ve Ormancılık",
      "Türkiye'de Madenler ve Enerji Kaynakları",
      "Türkiye'de Sanayi",
      "İlk Kültür Merkezleri",
      "Medeniyetlerin Merkezi Türkiye",
      "Kültür Bölgeleri ve Türk Kültürü",
      "Küresel Ticaret ile Hammadde, Üretim ve Pazar İlişkisi",
      "Turizm Faaliyetlerinin Ülkeler Arası Etkileşimde Rolü",
      "Ülkelerin Sanayileşme Süreçleri, Tarım-Ekonomi İlişkisi",
      "Bölgesel ve Küresel Örgütler",
      "Çevre Sorunlarının Oluşum Sebepleri",
      "Doğal Kaynak Kullanımı ve Çevresel Etkileri",
      "Arazi Kullanımına İlişkin Farklı Uygulamaların Çevre Üzerindeki Etkileri",
      "Atıklardan Korunma Yöntemleri",
      "Doğal Kaynakların Sürdürülebilir Kullanımı",
      "Geri Dönüşüm"
    ],
    "İngilizce": [
      "Future Jobs",
      "Hobbies and Skills",
      "Hard Times",
      "What a Life",
      "Back to the Past",
      "Open Your Heart",
      "Facts from Turkey",
      "Sports",
      "My Friends",
      "Values and Norms"
    ],
    "Psikoloji": [
      "Psikolojinin Konusu",
      "Psikolojinin Bilim Dalı Olma Süreci",
      "Ölçütler ve Amaçlar",
      "Araştırma Yöntem ve Teknikleri",
      "Etik Kurallar",
      "Psikolojinin Alt Dalları",
      "Psikolojinin İş Alanları",
      "Psikolojinin Diğer Bilimlerle İlişkisi",
      "Davranışın Oluşumu",
      "Psikolojik Süreçlerle Biyolojik Yapı ve Süreçlerin İlişkisi",
      "Kalıtım ve Çevrenin Psikolojik Süreçler ve Davranışa Etkisi",
      "Yaşam Boyu Gelişim Gelişim Dönemleri",
      "Ergenlik Dönemi",
      "Duyum ve Bilgi Arasındaki İlişki",
      "Uyarılma ve Davranış",
      "Alışma ve Duyarlılaşma",
      "Algılama Nedir?",
      "Algıyı Etkileyen Etmenler",
      "Duyum ve Algı Arasındaki Farklar",
      "Güdülenme",
      "Kendini Gerçekleştirmenin Önemi",
      "Duygular ve Türleri",
      "Duyguların Davranışa Etkisi",
      "Bilinç ve Bilinçaltı",
      "Dikkat Nedir?",
      "Farklı Bilinç Durumları",
      "Sosyal Psikoloji ve Sosyoloji Arasındaki Fark",
      "Sosyal Etkiler",
      "Davranış ve Sosyal Etki",
      "Öğrenme Nedir?",
      "Öğrenme Türleri",
      "Öğrenme ve Yaşam",
      "Öğrenmeyi Etkileyen Etmenler",
      "Öğrenme Stratejileri",
      "Hayat Boyu Öğrenme",
      "Bellek Türleri",
      "Öğrenme – Bellek – Hatırlama İlişkisi",
      "Düşünmenin Yapıtaşları",
      "Dil ve Düşünme",
      "Doğru Karar Verme ve İrdeleme",
      "Zeka ve Türleri",
      "Zeka ve Yaratıcılık",
      "Kişilik ve Kişilik Gelişimi",
      "Kişilik Kuramları",
      "Bireysel Farklılıklar",
      "Kişiliğin Değerlendirilmesi",
      "Stres nedir?",
      "Stresin Günlük Yaşama Etkileri",
      "Stresle Başa Çıkma Davranışı ve Savunma Mekanizmaları",
      "Ruh Sağlığı",
      "Normal ve Normal Dışı Davranış Türleri",
      "Psikolojik Destek Türleri"
    ],
    "Sosyoloji": [
      "Sosyoloji Nedir?",
      "Sosyoloji ve Toplum",
      "Sosyolojinin Doğuşu",
      "Sosyolojinin Yöntem ve Teknikleri",
      "Sosyalleşme Kavramı",
      "Sosyalleşme Sürecini Etkileyen Unsurlar",
      "Sosyalleşme, Yaşam ve Toplumsal İlişkiler",
      "Toplumsal Konum, Statü, Rol ve Saygınlık",
      "Toplumsal Değerler ve Normlar",
      "Toplumsal Kontrol",
      "Toplumsal Sapma",
      "Toplumsal Yapıyı Oluşturan Ögeler",
      "Toplumsal Etkileşim Tipleri",
      "Toplumsal Tabakalaşma",
      "Toplumsal Hareketlilik ve Çeşitleri",
      "Toplumsal Değişme",
      "Toplumsal Değişmeyi Etkileyen Faktörler",
      "Bilim, Teknoloji ve Kitle İletişim Araçları",
      "Modernleşme ve Küreselleşme",
      "Toplumsal Gelişme ve Öğeleri",
      "Toplumsal Bütünleşmenin Önemi",
      "Toplumsal Çözülmenin Nedenleri ve Çözüm Önerileri",
      "Kültürün Farklı Anlamları",
      "Kültürün Öğeleri",
      "Kültürün İşlevleri",
      "Kültürün Toplumsal Bütünleşmeye Katkısı",
      "Kültürün Temel Kavramları",
      "Kültürün Temel Kavramları Arasındaki İlişki",
      "Kültürlenme ve Kültürleşme",
      "Toplumların Farklı Kültürel Tutumları",
      "Kültürler Arası Etkileşim",
      "Toplumsal Kurum Nedir?",
      "Toplumsal Kurumların İşlevleri",
      "Toplumsal Yaşam, Sosyalleşme ve Aile",
      "Evlilik ve Boşanma Ailenin Sürekliliği",
      "Aile Modelleri",
      "Kadın, Aile ve Toplum",
      "Atatürk'ün Kadın Haklarına Verdiği Önem",
      "Eğitimin Toplumsal Yaşam ve Sosyalleşme Sürecindeki Önemi",
      "Atatürk ve Eğitim",
      "Din, Toplumsal Yaşam, Atatürk ve Laiklik",
      "Ekonomi ve Toplumsal Yaşam",
      "Ekonominin Bileşenleri",
      "Ekonomik Sistemler ve Atatürk'ün Ekonomik Sistemlerle İlgili Görüşleri",
      "Siyaset Kurumu ve Temel Kavramları",
      "Siyasal Yönetim Biçimleri",
      "Demokrasi ve Toplumsal Yaşam",
      "Atatürkçü Düşünce Sisteminde Vatandaşlık Hak ve Sorumlulukları"
    ],
    "Din Kültürü": [
      "Varoluşun ve Hayatın Anlamı",
      "Ahiret Alemi",
      "Ahirete Uğurlama Vefat edenin vasiyet ve borçları",
      "Tekfin ve teçhiz",
      "Cenaze namazı",
      "Taziye ve Kur'an okuma",
      "Dua etmek",
      "Hayır yapmak",
      "Kur'an'dan Mesajlar: Bakara Suresi 153-157. Ayetler",
      "Hz. Muhammed'in Şahsiyeti",
      "Hz. Muhammed'in Peygamberlik Yönü",
      "Hz. Muhammed'e Bağlılık ve İtaat",
      "Kur'an'dan Mesajlar: Ahzâb Suresi 45-46. Ayetler",
      "İslam'ın Aydınlık Yolu: Hidayet",
      "Allah'ı Görüyormuşçasına Yaşamak: İhsan",
      "Allah İçin Samimiyet: İhlas",
      "Allah'ın Emir ve Yasaklarına Riayet: Takva",
      "Dosdoğru Yol: Sırat-ı Müstakim",
      "Allah Yolunda Mücahede: Cihat",
      "İyi, Doğru ve Güzel Davranış: Salih Amel",
      "Kur'an'dan Mesajlar: Kehf Suresi 107-110. Ayetler",
      "İnançla İlgili Felsefi Yaklaşımlar",
      "Yeni Dini Hareketler",
      "Kur'an'dan Mesajlar: Enam Suresi 59. Ayet ve Lokman Suresi 27. Ayet",
      "Yahudilik",
      "Hıristiyanlık"
    ]
  },
  "12. Sınıf": {
    "Edebiyat": [
      "Edebiyat-Felsefe İlişkisi",
      "Edebiyat-Psikoloji İlişkisi",
      "Dilin Tarihi Süreç İçerisindeki Değişimini Etkileyen Sebepler",
      "İlk Örneklerden Günümüze Türkçe'nin Önemli Sözlükleri",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "1960 Sonrası Cumhuriyet Dönemi'nde Hikaye",
      "Küçürek (Minimal) Hikaye",
      "Kelimede Anlam",
      "Cumhuriyet Dönemi Saf Şiir Anlayışı",
      "Cumhuriyet Dönemi Toplumcu Eğilimleri Yansıtan Şiir Anlayışı",
      "Milli Edebiyat Anlayışını Yansıtan Şiir",
      "Garip Akımını Temsil Eden Şiir",
      "İkinci Yeni Şiiri",
      "Dini Değerleri, Geleneğe Duyarlığı ve Metafizik Anlayışı Öne Çıkaran Şiir",
      "1960 Sonrası Toplumcu Eğilimleri Öne Çıkaran Şiir",
      "1980 Sonrası Türk Şiir",
      "Cumhuriyet Sonrası Halk Şiiri",
      "Cumhuriyet Dönemi Türk Edebiyatı (1923-1950 Arası) Türk Romanı",
      "Cumhuriyet Dönemi Türk Edebiyatı (1950-1980 Arası) Türk Romanı",
      "1980 Sonrası Türk Edebiyatında Roman",
      "Türk Dünyası Edebiyatında Roman",
      "Dünya Edebiyatında Roman",
      "Paragrafta Anlam",
      "1950 Sonrası Türk Tiyatrosu",
      "Deneme Nedir?",
      "Dünya Edebiyatında Deneme",
      "Cumhuriyet Dönemi'nde (1923-1960 Arası) Deneme",
      "Cumhuriyet Dönemi'nde (1960 Sonrası) Deneme",
      "Söylev (Nutuk) Nedir?",
      "Cumhuriyet Dönemi'nde Söylev",
      "İslamiyet'in Kabulünden Önceki Türk Edebiyatında Söylev",
      "İslamiyet Etkisinde Gelişen Türk Edebiyatında Söylev"
    ],
    "Matematik": [
      "Üstel Fonksiyon",
      "Logaritmik Fonksiyon",
      "Üstel, Logaritmik Denklemler ve Eşitsizlikler",
      "Diziler",
      "Trigonometri",
      "Analitik Düzlemde Temel Dönüşümler",
      "Limit",
      "Süreklilik",
      "Türev",
      "Anlık Değişim Oranı ve Türev",
      "Türevin Uygulamaları",
      "Belirsiz İntegral",
      "Çemberin Analitik İncelemesi"
    ],
    "Fizik": [
      "Çizgisel Hız, Açısal Hız",
      "Merkezcil Kuvvet, Merkezcil İvme",
      "Eylemsizlik Momenti",
      "Açısal Momentum",
      "Kütle Çekim Kuvveti",
      "Uzanım, Genlik",
      "Geri Çağırıcı Kuvvet",
      "Denge Noktası",
      "Yay Sarkacı, Basit Sarkaç",
      "Girişim, Kırınım",
      "Doppler Olayı",
      "Elektromanyetik Dalga",
      "Elektromanyetik Spektrum",
      "Atom, Bohr Atom Teorisi",
      "Enerji Seviyesi",
      "Uyarılma, İyonlaşma, Işıma",
      "Büyük patlama",
      "Alt parçacık, Antimadde",
      "Radyoaktivite",
      "Fisyon, Füzyon",
      "Özel Görelilik",
      "Siyah Cisim Işıması",
      "Fotoelektrik Olayı",
      "Compton Olayı",
      "de Broglie Dalga Boyu",
      "Görüntüleme Teknolojisi",
      "Yarı İletken",
      "Diyot, Transistör",
      "LED",
      "Güneş Pili",
      "Süper İletken",
      "Nanoteknoloji",
      "Nanobilim",
      "LASER"
    ],
    "Kimya": [
      "İndirgenme Yükseltgenme Tepkimelerinde Elektrik Akımı",
      "Elektrotlar ve Elektrokimyasal Hücreler",
      "Elektrot Potansiyelleri",
      "Kimyasallardan Elektrik Üretimi",
      "Elektroliz",
      "Korozyon",
      "Anorganik ve Organik Bileşikler",
      "Basit Formül ve Molekül Formülü",
      "Doğada Karbon",
      "Lewis Formülleri",
      "Hibritleşme-Molekül Geometrisi",
      "Hidrokarbonlar",
      "Fonksiyonel",
      "Hidrokarbonlar",
      "Fonksiyonel Gruplar",
      "Alkoller",
      "Eterler",
      "Karbonil Bileşikleri",
      "Karboksilik Asitler",
      "Esterler",
      "Fosil Yakıtlar",
      "Alternatif Enerji Kaynakları"
    ],
    "Biyoloji": [
      "Nükleik Asitler",
      "Protein Sentezi",
      "Genetik Uygulamaları",
      "Fotosentez",
      "Fotosentez ve Kemosentez",
      "Solunum",
      "Fotosentez ve Solunumun Karşılaştırılması",
      "Bitkisel Yapılar",
      "Bitkisel Hormonlar",
      "Bitkilerde Madde Taşınması",
      "Bitkilerde Üreme",
      "Canlılar ve Çevre"
    ],
    "Çağdaş Tarih": [
      "I. Dünya Savaşı ve Sonuçları",
      "Sovyet Sosyalist Cumhuriyetler Birliği (SSBC), Orta Asya'daki Türk Devletler ve Toplulukları",
      "Orta Doğu'da Manda Yönetiminin Kurulması",
      "Uzak Doğu'da Yeni Bir Güç: Japonya",
      "1929 Dünya Ekonomik Krizi",
      "İki Savaş Arası Dönemde Avrupa",
      "İki Savaş Arası Dönemde Dünya",
      "Atatürk Dönemi Türk Dış Politikası",
      "Yeni Bir Savaşa Doğru",
      "Savaş Yılları",
      "Barışa Doğru",
      "Savaşın Etkileri",
      "Savaş Yıllarında Türkiye",
      "Blokların Kuruluşu",
      "Paylaşılmayan Orta Doğu",
      "Uzak Doğu'da Çatışma",
      "Asya ve Afrika'nın Kurtuluşu",
      "Soğuk Savaş Döneminde Türkiye",
      "Soğuk Savaş Döneminde Dünya",
      "Uluslararası İlişkilerde Değişim Süreci",
      "Yumuşama Dönemi Çatışmaları",
      "Barış İçinde Bir Arada Yaşama",
      "Arap-İsrail Savaşları ve Büyük Devletlerin Politikaları",
      "Uluslararası Politikada Petrolün Yeri",
      "İran-Irak Savaşı",
      "Yumuşama Döneminde Dünya",
      "Türk Dış Politikası",
      "Türkiye'de Bunalımlı Yıllar",
      "SSCB'de Değişen ve Sonuçları",
      "Asya'da Yeni Yapılanma",
      "Doğu Bloku'dan Sonra Avrupa'da Yeni Arayışlar",
      "Türkiye ve Avrupa Birliği",
      "Yeni Oluşum Sürecinde Balkanlar",
      "Orta Doğu ve Afganistan'da ki Gelişmeler",
      "Dünyadaki Gelişmeler",
      "Değişen Dünya ve Türk Dış Politikası",
      "1980 Sonrası Türkiye",
      "Küresel Sorunlar"
    ],
    "İnkılap Tarihi": [
      "20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Milli Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
      "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
      "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
      "Toplumsal Devrim Çağında Dünya ve Türkiye",
      "21. Yüzyılın Eşiğinde Türkiye ve Dünya"
    ],
    "Coğrafya": [
      "Ekstrem Doğa Olayları",
      "Doğal Sistemlerdeki Değişimlerin Geleceğe Etkisi",
      "Şehirleşme, Göç ve Sanayi İlişkisinin Toplumsal Etkileri",
      "Türkiye'deki Bölgesel Kalkınma Projeleri ve İşlevsel Bölgeler",
      "Ulaşım Sistemlerinin Gelişimini Etkileyen Faktörler",
      "Türkiye'de Ulaşım Sistemlerinin Gelişimi",
      "Dünya Ticaret Merkezleri ve Türkiye'de Ticaret",
      "Türkiye'yi Sembolize Eden Doğal ve Kültürel Değerler",
      "Türkiye'nin Turizm Potansiyeli ve Politikaları",
      "Kıtaların, Okyanusların ve Ülkelerin Konumunun Küresel ve Bölgesel Önemi",
      "Türkiye'nin Jeopolitiği ve Türk Kültür Bölgeleri ile Türkiye İlişkisi",
      "Gelişmişlik Seviyelerine Göre Ülkeler",
      "Gelişmiş ve Gelişmekte Olan Ülkelerin Ekonomik Özellikleri",
      "Ülkelerin Doğal Kaynak Potansiyelinin Küresel ve Bölgesel İlişkilerine Etkisi",
      "Enerji Taşımacılığı",
      "Ülkeler Arasında Sorun Oluşturan Mekânsal Unsurlar ve Sıcak Çatışma Bölgeleri",
      "Doğal Çevrenin Sınırlılığı ve Sürdürülebilirlik",
      "Doğal ve Kültürel Mirasın Korunması ve Çevre Bilinci"
    ],
    "İngilizce": [
      "Music",
      "Friendship",
      "Human Rights",
      "Coming Soon",
      "Psychology",
      "Favors",
      "News Stories",
      "Alternative Energy",
      "Technology",
      "Manners"
    ],
    "Mantık": [
      "Mantık ve Doğru Düşünme",
      "Akıl İlkeleri",
      "Akıl Yürütmede Kullanılan Temel Terimler",
      "Akıl Yürütme Yöntemleri",
      "Mantık ve Pratik Yaşam",
      "Mantık ve Teknoloji",
      "Mantık ve Bilimsel Yöntem",
      "Kavram Nedir?",
      "Kavram ve Terim İlişkisi",
      "Nelik, Gerçeklik, Kimlik",
      "İçlem ve Kaplam",
      "Kavram Çeşitleri",
      "Beş Tümel",
      "Kavramlar Arasındaki İlişkiler",
      "Tanım",
      "Önerme Olan ve Olmayan Cümleler",
      "Önerme Çeşitleri",
      "Çıkarım Nedir?",
      "Doğrudan Çıkarım",
      "Karşı Olum Çıkarımları",
      "Döndürme",
      "Dolaylı Çıkarım",
      "Kıyas Nedir?",
      "Kıyas Kuralları",
      "Kıyasta Mantıksal Zorunluluk ve Olasılık",
      "Kıyas Çeşitleri",
      "Dilin İşlevleri",
      "Çok Anlamlılık",
      "Anlam Belirsizliği",
      "Anlam Belirsizliğinin Sakıncaları",
      "Olgusal ve Sözsel Tartışmalar",
      "Anlama ve Tanımlama",
      "Sembolik Mantığa Giriş",
      "Önermeler Mantığı",
      "Önerme ve Yapısı",
      "Basit ve Bileşik Önermeler",
      "Önerme Eklemleri",
      "Klasik ve Sembolik",
      "Mantıkta Çıkarım",
      "Sembolleştirme",
      "Doğruluk Değerini Yorumlama",
      "Doğruluk Çizelgesi",
      "Tutarlılık",
      "Geçerlilik",
      "Eşdeğerlik",
      "Çözümleyici Çizelge Kuralları",
      "Niceleme (Yüklemler) Mantığı",
      "Sembolleştirme",
      "Temel Kavramlar",
      "Temel Kurallar",
      "Çok Değerli Mantık",
      "Üç Değerli Mantık",
      "Bulanık Mantık"
    ],
    "Din Kültürü": [
      "Din-Bilim İlişkisi",
      "İslam Medeniyetinde Bilim ve Düşüncenin Gelişimi",
      "İslam Medeniyetinde Öne Çıkan Eğitim Kurumları",
      "Müslümanların Bilim Alanında Yaptığı Öncü ve Özgün Çalışmalar",
      "Kur'an'dan Mesajlar: Fâtır Suresi 27-28. Ayetler",
      "Türklerin Müslüman Olmaları",
      "Milletimizin İslam Anlayışının Oluşmasında Etkili Olan Bazı Şahsiyetler: Ebu Hanife",
      "Cafer es-Sadık",
      "Maturidi",
      "Şafii",
      "Eş'ari",
      "Ahmet Yesevi",
      "Mevlana Celaleddin-i Rumi",
      "Ahi Evran",
      "Hacı Bektaş-ı Veli",
      "Yunus Emre",
      "Sarı Saltuk",
      "Hacı Bayram-ı Veli",
      "Kur'an'dan Mesajlar: Nisâ Suresi 69. Ayet",
      "Tasavvufi Düşüncenin Oluşumu",
      "Tasavvufi Düşüncenin Ahlaki Boyutu",
      "Kültürümüzde Etkin Olan Tasavvufi Yorumlar: Yesevilik",
      "Kadirilik",
      "Rifailik",
      "Mevlevilik",
      "Nakşibendilik",
      "Alevilik-Bektaşilik",
      "Kur'an'dan Mesajlar: Hucurât Suresi 10. Ayet",
      "Dini Meselelerin Çözümünde Temel İlke ve Yöntemler",
      "İktisadi Hayatla İlgili Meseleler",
      "Gıda Maddeleri ve Bağımlılıkla İlgili Meseleler",
      "Sağlık ve Tıpla İlgili Meseleler",
      "Kur'an'dan Mesajlar: En'âm suresi 151-152. Ayetler",
      "Hinduizm",
      "Budizm",
      "Konfüçyanizm",
      "Taoizm"
    ]
  }
};

/**
 * Bir konunun müfredatta olup olmadığını kontrol eder
 * @param examType - Sınav türü veya sınıf seviyesi (örn: "TYT", "AYT", "12. Sınıf")
 * @param subject - Ders adı (örn: "Matematik")
 * @param topic - Konu adı (örn: "Türev")
 * @returns true if topic is in curriculum, false otherwise
 */
export function isTopicInCurriculum(
  examType: string,
  subject: string,
  topic: string
): boolean {
  const curriculum = CURRICULUM[examType];
  if (!curriculum) return false;

  const subjectTopics = curriculum[subject];
  if (!subjectTopics) return false;

  // Normalize comparison for case-insensitive matching
  const normalizedTopic = normalizeTopicName(topic);
  return subjectTopics.some(t => normalizeTopicName(t) === normalizedTopic);
}

/**
 * Normalized string comparison for topic matching
 * Case-insensitive, trims whitespace, and handles Turkish characters
 */
export function normalizeTopicName(topic: string): string {
  return topic
    .trim()
    .toLowerCase()
    .replace(/ğ/g, 'g')
    .replace(/ü/g, 'u')
    .replace(/ş/g, 's')
    .replace(/ı/g, 'i')
    .replace(/ö/g, 'o')
    .replace(/ç/g, 'c')
    .replace(/\s+/g, ' ');
}

/**
 * Belirli bir sınav türü veya sınıf için dersleri döndürür
 * @param examType - Sınav türü veya sınıf seviyesi (örn: "TYT", "AYT", "12. Sınıf")
 * @returns Ders adları dizisi
 */
export function getSubjectsForExamType(examType: string): string[] {
  const curriculum = CURRICULUM[examType];
  if (!curriculum) return [];
  return Object.keys(curriculum);
}

/**
 * Belirli bir sınav türü ve ders için konuları döndürür
 * @param examType - Sınav türü veya sınıf seviyesi (örn: "TYT", "AYT", "12. Sınıf")
 * @param subject - Ders adı (örn: "Matematik")
 * @returns Konu adları dizisi
 */
export function getTopicsForSubject(examType: string, subject: string): string[] {
  const curriculum = CURRICULUM[examType];
  if (!curriculum) return [];
  return curriculum[subject] || [];
}

/**
 * Tüm müfredat konularını düz bir liste olarak döndürür
 */
export function getAllTopics(): string[] {
  const allTopics: string[] = [];
  for (const examType in CURRICULUM) {
    for (const subject in CURRICULUM[examType]) {
      allTopics.push(...CURRICULUM[examType][subject]);
    }
  }
  return allTopics;
}

/**
 * Tüm sınav türlerini ve sınıfları döndürür
 */
export function getAllExamTypes(): string[] {
  return Object.keys(CURRICULUM);
}
