// Türkiye YKS Müfredat Sabitleri
// Konu Hakimiyeti ve AI Görev Önericisi için kullanılır

export const YKS_CURRICULUM = {
  "Türkçe": [
    "Sözcükte Anlam",
    "Cümlede Anlam",
    "Paragraf",
    "Ses Bilgisi",
    "Yazım Kuralları",
    "Noktalama İşaretleri",
    "Sözcük Türleri",
    "Cümle Türleri",
    "Anlatım Bozuklukları",
    "Fiil Çatısı",
    "Sentence Transformation",
    "Koşul Bağlaçları",
    "Edilgen Çatı",
    "Nitelik Sıfatı",
    "Sıfat Fiil",
    "Zarf Fiil",
    "Zarf",
    "Zamirler",
    "Bağlaçlar",
    "Preposition",
    "Conjunction",
    "Articles",
    "Narrative Tenses",
    "Wish Clauses",
    "Conditionals",
    "Passive Voice",
    "Relative Clauses",
    "Inversion",
    "Gerunds and Infinitives",
    "Participles",
    "Reported Speech",
    "Causative"
  ],
  "Matematik": [
    "Temel Kavramlar",
    "Sayılar",
    "Üslü Sayılar",
    "Köklü Sayılar",
    "Çarpanlara Ayırma",
    "Oran-Orantı",
    "Denklemler",
    "Eşitsizlikler",
    "Basit Eşitsizlikler",
    "Mutlak Değer",
    "Parabol",
    "Üstün Fonksiyonlar",
    "Trigonometri",
    "Sinüs ve Kosinüs Teoremleri",
    "Trigonometrik Fonksiyonlar",
    "Trigonometrik Denklemler",
    "Logaritma",
    "Üstel Fonksiyonlar",
    "Diziler",
    "Aritmetik Diziler",
    "Geometrik Diziler",
    "Limit",
    "Türev",
    "İntegral",
    "Türev Uygulamaları",
    "İntegral Uygulamaları",
    "Kombinasyon",
    "Permutasyon",
    "Olasılık",
    "İstatistik",
    "Analitik Geometri",
    "Koordinat Düzlemi",
    "Doğru",
    "Daire",
    "Konikler",
    "Kompleks Sayılar",
    "Polinomlar"
  ],
  "Fizik": [
    "Kuvvet ve Hareket",
    "Vektörler",
    "Newton Hareket Yasaları",
    "Dinamik",
    "İş-Güç-Enerji",
    "İş",
    "Güç",
    "Enerji",
    "Kinetik Enerji",
    "Potansiyel Enerji",
    "Enerji Korunumu",
    "Basit Makineler",
    "Momentum",
    "İmpuls",
    "Basit Harmonik Hareket",
    "Dalga Hareketi",
    "Ses",
    "Işık",
    "Optik",
    "Aynalar",
    "Mercekeler",
    "Elektrik",
    "Elektrik Alanı",
    "Potansiyel",
    "Kapasitans",
    "Akım",
    "Ohm Yasası",
    "Manyetizma",
    "Elektromanyetik İndüksiyon",
    "Alternatif Akım",
    "Modern Fizik",
    "Atom Fiziği",
    "Çekirdek Fiziği",
    "Radyoaktivite",
    "Görelilik"
  ],
  "Kimya": [
    "Temel Kavramlar",
    "Atom Yapısı",
    "Periyodik Sistem",
    "Kimyasal Türler",
    "Mol Kavramı",
    "Kimyasal Tepkimeler",
    "Asit-Baz",
    "pH",
    "Titrasyon",
    "Çözünürlük",
    "Gazlar",
    "Sıvılar",
    "Katılar",
    "Organik Kimya",
    "Hidrokarbonlar",
    "Alkoller",
    "Aldehitler",
    "Ketonlar",
    "Karboksilik Asitler",
    "Esterler",
    "Organik Reaksiyonlar",
    "Polimerler",
    "Kimyasal Termodinamik",
    "Kimyasal Kinetik",
    "Denge",
    "Elektrokimya",
    "Metal ve Alaşımlar",
    "Doğal Kaynaklar"
  ],
  "Biyoloji": [
    "Canlıların Ortak Özellikleri",
    "Hücre",
    "Hücre Organelleri",
    "Hücre Bölünmesi",
    "Mitoz",
    "Eşeysiz Üreme",
    "Eşeysel Üreme",
    "Kalıtım",
    "Mendel Yasaları",
    "DNA",
    "RNA",
    "Genetik Kod",
    "Mutasyon",
    "Bitki Biyolojisi",
    "Hayvan Biyolojisi",
    "İnsan Biyolojisi",
    "Sinir Sistemi",
    "Endokrin Sistem",
    "Dolaşım Sistemi",
    "Solunum Sistemi",
    "Sindirim Sistemi",
    "Boşaltım Sistemi",
    "Ekosistem",
    "Besin Zinciri",
    "Ekolojik Dengeler",
    "Canlılarda Enerji",
    "Fotosentez",
    "Solunum",
    "Üretim ve Alım",
    "Bitki Sınıflandırması",
    "Hayvan Sınıflandırması",
    "Virusler",
    "Bakteriler",
    "Mantarlar",
    "Protistler"
  ],
  "Tarih": [
    "İlk Çağlar",
    "Tarih Öncesi",
    "İlk Uygarlıklar",
    "Antik Çağ",
    "Mısır",
    "Mezopotamya",
    "Anadolu Medeniyetleri",
    "Hititler",
    "Frigler",
    "Urartular",
    "Lidyalılar",
    "İonya",
    "Lykia",
    "Karya",
    "Pisidia",
    "Pamphylia",
    "Kilikya",
    "Kapadokya",
    "Galatya",
    "Romalılar Dönemi",
    "Bizans Dönemi",
    "Türk-İslam Tarihi",
    "İlk Türk Devletleri",
    "İslam Tarihi",
    "Selçuklular",
    "Osmanlı Devleti",
    "Kuruluş",
    "Yükseliş",
    "Duraklama",
    "Gerileme",
    "Osmanlı Kültür ve Medeniyeti",
    "Kurtuluş Savaşı",
    "Türkiye Cumhuriyeti Tarihi",
    "Atatürk İlkeleri",
    "Türkiye Dünya İlişkileri",
    "Soğuk Savaş",
    "Modern Türk Tarihi"
  ],
  "Coğrafya": [
    "Temel Kavramlar",
    "Harita Bilgisi",
    "Koordinat Sistemi",
    "Dünya'nın Şekli",
    "Hareketleri",
    "Atmosfer",
    "İklim",
    "Sıcaklık",
    "Basınç",
    "Rüzgarlar",
    "Yağışlar",
    "Su Küreleri",
    "Nehirler",
    "Göller",
    "Denizler",
    "Okyanuslar",
    "İç Sular",
    "Kıtalar",
    "Türkiye Coğrafyası",
    "Yer Şekilleri",
    "Bölgeler",
    "Nüfus",
    "Yerleşme",
    "Ulaştırma",
    "Tarım",
    "Hayvancılık",
    "Sanayi",
    "Ticaret",
    "Turizm",
    "Çevre Sorunları",
    "Doğal Afetler"
  ],
  "Felsefe": [
    "Felsefeyi Tanımlama",
    "Felsefenin Konuları",
    "Felsefenin Yöntemi",
    "Antik Yunan Felsefesi",
    "Sokrates",
    "Platon",
    "Aristoteles",
    "Helenistik Dönem",
    "Orta Çağ Felsefesi",
    "İslam Felsefesi",
    "Hristiyan Felsefesi",
    "Yeni Çağ Felsefesi",
    "Rasyonalizm",
    "Ampirizm",
    "Aydınlanma",
    "Alman İdealizmi",
    "Varlık Felsefesi",
    "Bilgi Felsefesi",
    "Ahlak Felsefesi",
    "Sanat Felsefesi",
    "Din Felsefesi",
    "Siyaset Felsefesi",
    "Modern Felsefe",
    "Varoluşçuluk",
    "Fenomenoloji",
    "Yapısalcılık",
    "Postmodernizm"
  ],
  "Din Kültürü": [
    "Din ve İnanç",
    "İbadet",
    "İslam",
    "İslam'ın Kaynakları",
    "İslam'ın Temel Esasları",
    "İbadetler",
    "Hz. Muhammed'in Hayatı",
    "İslam Tarihine Genel Bakış",
    "Hristiyanlık",
    "Yahudilik",
    "Budizm",
    "Hinduizm",
    "Türk İslam Kültürü",
    "Selçuklular Dönemi",
    "Osmanlı Dönemi",
    "Cumhuriyet Dönemi",
    "Alevilik",
    "Sünnilik",
    "Din ve Ahlak",
    "Din ve Toplum",
    "Din ve Bilim",
    "İnanç ve Sosyal Yaşam"
  ],
  "İngilizce": [
    "Grammar",
    "Tenses",
    "Present Simple",
    "Present Continuous",
    "Past Simple",
    "Past Continuous",
    "Present Perfect",
    "Past Perfect",
    "Future Tenses",
    "Conditionals",
    "Passive Voice",
    "Reported Speech",
    "Relative Clauses",
    "Noun Clauses",
    "Adverbial Clauses",
    "Modals",
    "Articles",
    "Prepositions",
    "Conjunctions",
    "Vocabulary",
    "Word Formation",
    "Collocations",
    "Phrasal Verbs",
    "Idioms",
    "Reading",
    "Skimming",
    "Scanning",
    "Reading Comprehension",
    "Writing",
    "Essay Writing",
    "Paragraph Writing",
    "Letter Writing",
    "Listening",
    "Note-taking",
    "Speaking",
    "Pronunciation",
    "Intonation"
  ]
} as const;

export const SUBJECTS = Object.keys(YKS_CURRICULUM);

export function getTopicsForSubject(subject: string): string[] {
  return YKS_CURRICULUM[subject as keyof typeof YKS_CURRICULUM] || [];
}