export const TURKISH_UNIVERSITIES = [
  // Devlet Üniversiteleri
  "Abant İzzet Baysal Üniversitesi",
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Aksaray Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Ardahan Üniversitesi",
  "Atatürk Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bartın Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bingöl Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çorum Hitit Üniversitesi",
  "Dicle Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Edirne Trakya Üniversitesi",
  "Ege Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Erzurum Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Fırat Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gazi Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hakkari Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Iğdır Üniversitesi",
  "Isparta Süleyman Demirel Üniversitesi",
  "İstanbul Beykent Üniversitesi",
  "İstanbul Cerrahpaşa Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Katip Çelebi Üniversitesi",
  "Kafkas Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Karabük Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kayseri Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırşehir Ahi Evran Üniversitesi",
  "Kocaeli Üniversitesi",
  "Konya Necmettin Erbakan Üniversitesi",
  "Konya Selçuk Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kırklareli Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Muş Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ordu Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Pamukkale Üniversitesi",
  "Piri Reis Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sakarya Üniversitesi",
  "Samsun Ondokuz Mayıs Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Şırnak Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Trakya Üniversitesi",
  "Tunceli Üniversitesi",
  "Uşak Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",

  // Vakıf Üniversiteleri
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Acıbadem Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Altınbaş Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Arel Üniversitesi",
  "Atılım Üniversitesi",
  "Avrasya Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Başkent Üniversitesi",
  "Bezmialem Vakıf Üniversitesi",
  "Beykent Üniversitesi",
  "Beykent Üniversitesi",
  "Bilgi Üniversitesi",
  "Bilkent Üniversitesi",
  "Biruni Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Çağ Üniversitesi",
  "Çankaya Üniversitesi",
  "Doğuş Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Dumlupınar Üniversitesi",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gedik Üniversitesi",
  "Gelişim Üniversitesi",
  "Girne Amerikan Üniversitesi",
  "Girne Üniversitesi",
  "Haliç Üniversitesi",
  "Hakkari Üniversitesi",
  "Harran Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Ibn Haldun Üniversitesi",
  "Iğdır Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Şehir Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul University",
  "İzmir Ekonomi Üniversitesi",
  "İzmir University",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kadir Has Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Kapadokya Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kıbrıs Amerikan Üniversitesi",
  "Kıbris International University",
  "Kıbris Sosyal Bilimler Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kocaeli Üniversitesi",
  "Kocaeli Üniversitesi",
  "Konya Food and Agriculture University",
  "KTO Karatay Üniversitesi",
  "Kültür Üniversitesi",
  "Maltepe Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Mef Üniversitesi",
  "Mehmet Akif Ersoy Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ortadoğu Teknik Üniversitesi",
  "Orhan Gazi Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Özyeğin Üniversitesi",
  "Pamukkale Üniversitesi",
  "Sabancı Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Sakarya Üniversitesi",
  "Samsun Üniversitesi",
  "Şifa Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Turgut Özal Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Türk Hava Kurumu Üniversitesi",
  "Türkiye İmsak Sanatları Üniversitesi",
  "Ufuk Üniversitesi",
  "Üsküdar Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yalova Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yeni Yüzyıl Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yönetim Bilimleri Üniversitesi",
  "Yozgat Bozok Üniversitesi"
] as const;

export type TurkishUniversity = typeof TURKISH_UNIVERSITIES[number];
